#include QMK_KEYBOARD_H
#if __has_include("keymap.h")
#    include "keymap.h"
#endif


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

//define basic keycodes where tap and/or hold is not just a basic keycode
enum custom_keycodes {
    SPL = SAFE_RANGE, //open copy of browser window, in another window
    PIPE, // ||
    UP_DBL, //2 page up arrow
    DN_DBL, //2 page down arrow
    PGUP_DBL, //2 page scroll up, double page up when held
    PGDN_DBL, //2 page scroll down
    WKSP1, //workspace 1
    WKSP2, //workspace 2
    COLON, //fg + enter
    EQUAL, //ctrl + z
    PAR, // ()
    CUR, // {}
    SQU, // []
    QUO, // ''
    DBLQUO, // ""
    CAPG, // G
    ML, //left mouse
    SWITCH_TAB, //ctrl + tab
    PREV_TAB, //ctrl + shift + tab
    ADD_BAR, //ctrl l
    BASE_R, //baselayer and pressed letter R for vimium
    //NEW_TAB, //ctrl t
    CLOSE_TAB, //ctrl w
};

//define keycodes for customised tap-hold keys where tap AND hold function is a
//basic keycode. kc is the tap keycode in LT(0, kc). Cannot have 2 keycodes with
//same kc in the list - create custom kc in enum to have unique values but this
//would be more messy having another definition in enum list.
#define RARROW LT(0, KC_RGHT) //alt + right arrow when held
#define LARROW LT(0, KC_LEFT) //alt + left arrow when held
//old codes below to refactor into enum instead
#define PAR     LT(PAR, KC_0)   // () with arrow back function when held
#define CUR     LT(CUR, KC_0)   // {} with arrow back function when held
#define SQU     LT(SQU, KC_0)   // [] with arrow back function when held
#define QUO     LT(QUO, KC_0)   // '' with arrow back function when held
#define DBLQUO     LT(DBLQUO, KC_0)   // "" with arrow back function when held
#define PIPE     LT(PIPE, KC_0)   // || with arrow back function when held
#define WKSP1     LT(WKSP1, KC_0)   // workspace 3 function when held
#define WKSP2     LT(WKSP2, KC_0)   // workspace 4 function when held
#define COLON     LT(COLON, KC_0)   // fg + enter function when held
#define EQUAL     LT(EQUAL, KC_0)   // ctrl + z function when held
 
//Function for layer-tap key LT(0, kc), where kc is basic keycode
//Only works if both tap/hold have basic keycodes. Doesn't work if have list of
//keys to tap, etc.
//Used in switch/case statements
static bool process_tap_or_long_press_key(
  keyrecord_t* record, uint16_t long_press_keycode) {
  if (record->tap.count == 0) { //Key is being held
    if (record->event.pressed) {
      tap_code16(long_press_keycode);
    }
    return false; //skip default handling
  }
  return true;
}

bool process_record_user(uint16_t keycode, keyrecord_t *record) {
  switch (keycode) {
    case SPL:
    	if (record->event.pressed) {
        //using opposite hand modifier as same hand shift/control has 
        //been programmed to not work to prevent rollover 
        //accidental modifier trigger when typing
	      tap_code16(RCTL(KC_L));
    	  tap_code16_delay(LSFT(KC_ENT), 500);
	    }
     	return false;
	    break;
    case PIPE: 
      if (record->tap.count) {
        if(record->event.pressed) {
	        SEND_STRING("||" SS_TAP(X_LEFT));
        }
        return false;
        //if held
      } else if (record->event.pressed) {
        SEND_STRING("||");        
        return false;
      } 
      return false;
      break;
    case LT(0, PGUP_DBL):
      if (record->tap.count && record->event.pressed) {
          //if shift pressed, do double page arrow down
          if(get_mods() & MOD_BIT(KC_RSFT)) {
            unregister_mods(MOD_BIT(KC_RSFT));	
            tap_code(KC_UP);
            tap_code16(RGUI(KC_LEFT));
            tap_code(KC_UP);
            tap_code16(RGUI(KC_LEFT));
            add_mods(MOD_BIT(KC_RSFT));
            return false;
          //if no shift pressed
          } else {
            tap_code(KC_PGUP);
            return false;
          }
       return false; 
      //if held
      } else if (record->event.pressed) {
        tap_code(KC_PGUP);
        tap_code(KC_PGUP);
        tap_code16(RGUI(KC_LEFT));
        tap_code(KC_PGUP);
        tap_code(KC_PGUP);
      }
      return false;
      break;
    case LT(0, PGDN_DBL):
      if (record->tap.count) {
        if (record->event.pressed) {
          //if shift pressed, do double page arrow down
          if(get_mods() & MOD_BIT(KC_RSFT)) {
            unregister_mods(MOD_BIT(KC_RSFT));	
            tap_code(KC_DOWN);
            tap_code16(RGUI(KC_LEFT));
            tap_code(KC_DOWN);
            tap_code16(RGUI(KC_LEFT));
            add_mods(MOD_BIT(KC_RSFT));
            return false;
          //if no shift pressed
          } else {
            tap_code(KC_PGDN);
            return false;
          }
        }
      //if held
      } else if (record->event.pressed) {
        tap_code(KC_PGDN);
        tap_code(KC_PGDN);
        tap_code16(RGUI(KC_LEFT));
        tap_code(KC_PGDN);
        tap_code(KC_PGDN);
      }
      return false;
      break;
    //cancel rolled modifiers of same hand. Prevents modifiers accidental
    //press e.g. when press s and t key, stops ctrl + t behaviour.
    case LSFT_T(KC_T):
      if (record->event.pressed && record->tap.count > 0) {
        if (get_mods() & MOD_BIT(KC_LCTL)) {
          unregister_mods(MOD_BIT(KC_LCTL));
          tap_code(KC_S);
          tap_code(KC_T);
          add_mods(MOD_BIT(KC_LCTL));
          return false;
        }
      }
      layer_clear();
      return true;
     	break;
    case RSFT_T(KC_N):
      if (record->event.pressed && record->tap.count > 0) {
        if (get_mods() & MOD_BIT(KC_RCTL)) {
          unregister_mods(MOD_BIT(KC_RCTL));
          tap_code(KC_E);
          tap_code(KC_N);
          add_mods(MOD_BIT(KC_RCTL));
          return false;
        }
      }
      return true;
    	break;
    //enter goes back baselayer if layer set
    case KC_ENT:
      if (record->event.pressed) {
        if (IS_LAYER_ON(1) 
          || IS_LAYER_ON(2) 
          || IS_LAYER_ON(3)
          || IS_LAYER_ON(4)) {
          tap_code(KC_ENT);
          layer_clear();       
          return false;
        }
      }
      return true;
      break;
    //clears all layers if access symbol layer
    case LT(3,KC_SPC):
      //when key held d
      if (!record->tap.count) {
        if (IS_LAYER_ON(1) 
          || IS_LAYER_ON(2) 
          || IS_LAYER_ON(4)) {
          layer_clear();       
          return true;
        }
      }
      return true;
      break;
    case LT(3,KC_BSPC):
      if (!record->tap.count) {
        if (IS_LAYER_ON(1) 
          || IS_LAYER_ON(2) 
          || IS_LAYER_ON(4)) {
          layer_clear();       
          return true;
        }
      }
      return true;
      break;
    case TO(4):
      if (record->event.pressed) {
        if (IS_LAYER_ON(1) 
          || IS_LAYER_ON(2)) {
          layer_clear();       
          return true;
        }
      }
      return true;
      break;
    //escape goes back baselayer if layer set
    case KC_ESC:
      if (record->event.pressed) {
        //if (IS_LAYER_ON(1) || IS_LAYER_ON(2) || IS_LAYER_ON(4)) {
        layer_clear();       
        return true;
      }
      return true;
      break;
    case WKSP1: 
      layer_move(0);
      if (record->tap.count) {
        if(record->event.pressed) {
          register_mods(MOD_BIT(KC_RGUI));
          tap_code(KC_1);
          unregister_mods(MOD_BIT(KC_RGUI));
        }
        return false;
      //if held
      } else if (record->event.pressed) {
        register_mods(MOD_BIT(KC_RGUI));
        tap_code(KC_3);
        unregister_mods(MOD_BIT(KC_RGUI));
      }
      return false;
      break;
    case WKSP2: 
      layer_move(0);
      if (record->tap.count) {
        if(record->event.pressed) {
          register_mods(MOD_BIT(KC_RGUI));
          tap_code(KC_2);
          unregister_mods(MOD_BIT(KC_RGUI));
        }
        return false;
      } else if (record->event.pressed) {
        register_mods(MOD_BIT(KC_RGUI));
        tap_code(KC_4);
        unregister_mods(MOD_BIT(KC_RGUI));
      }
      return false;
      break;
    case COLON: 
      if (record->tap.count) {
        if(record->event.pressed) {
	        SEND_STRING(":");
        }
        return false;
        //if held fg + enter
      } else if (record->event.pressed) {
        SEND_STRING("fg");        
        tap_code(KC_ENT);
        return false;
      } 
      return false;
      break;
    case EQUAL: 
      if (record->tap.count) {
        if(record->event.pressed) {
	        SEND_STRING("=");
        }
        return false;
        //if held ctrl + z
      } else if (record->event.pressed) {
        register_mods(MOD_BIT(KC_RCTL));
        tap_code(KC_Z);
        unregister_mods(MOD_BIT(KC_RCTL));
        return false;
      } 
      return false;
      break;
    //macro for brackets
    case PAR: 
      if (record->tap.count) {
        if(record->event.pressed) {
	        SEND_STRING("()" SS_TAP(X_LEFT));
        }
        return false;
        //if held
      } else if (record->event.pressed) {
        SEND_STRING("()");        
        return false;
      } 
      return false;
      break;
    case CUR:
      if (record->tap.count) {
        if(record->event.pressed) {
	        SEND_STRING("{}" SS_TAP(X_LEFT));
        }
        return false;
        //if held
      } else if (record->event.pressed) {
        SEND_STRING("{}");        
        return false;
      } 
      return false;
      break;
    case SQU: 
      if (record->tap.count) {
        if(record->event.pressed) {
	        SEND_STRING("[]" SS_TAP(X_LEFT));
        }
        return false;
        //if held
      } else if (record->event.pressed) {
        SEND_STRING("[]");        
        return false;
      } 
      return false;
      break;
    //below needs to be added to combos to use right pinky keys
    case QUO: 
      if (record->tap.count) {
        if(record->event.pressed) {
	        SEND_STRING("''" SS_TAP(X_LEFT));
        }
        return false;
        //if held
      } else if (record->event.pressed) {
        SEND_STRING("''");        
        return false;
      } 
      return false;
      break;
    case DBLQUO: 
      if (record->tap.count) {
        if(record->event.pressed) {
	        SEND_STRING("\"\"" SS_TAP(X_LEFT));
        }
        return false;
        //if held
      } else if (record->event.pressed) {
        SEND_STRING("\"\"");        
        return false;
      } 
      return false;
      break;
    case CAPG: 
   	  if(record->event.pressed) {
        register_mods(MOD_BIT(KC_RSFT));
        tap_code(KC_G);
        layer_clear();
        unregister_mods(MOD_BIT(KC_RSFT));
        return false;
  	  } 
      return true;
	    break;
      /*
    case NEW_TAB: 
   	  if(record->event.pressed) {
        layer_clear();
        register_mods(MOD_BIT(KC_RCTL));
        tap_code(KC_T);
        unregister_mods(MOD_BIT(KC_RCTL));
        return false;
  	  } 
	    break;
      */
    case CLOSE_TAB: 
   	  if(record->event.pressed) {
        register_mods(MOD_BIT(KC_RCTL));
        tap_code(KC_W);
        unregister_mods(MOD_BIT(KC_RCTL));
        return false;
  	  } 
	    break;
    case SWITCH_TAB: 
   	  if(record->event.pressed) {
        register_mods(MOD_BIT(KC_RCTL));
        tap_code(KC_TAB);
        unregister_mods(MOD_BIT(KC_RCTL));
        return false;
  	  } 
	    break;
    case PREV_TAB: 
   	  if(record->event.pressed) {
        register_mods(MOD_BIT(KC_RCTL));
        register_mods(MOD_BIT(KC_RSFT));
        tap_code(KC_TAB);
        unregister_mods(MOD_BIT(KC_RCTL));
        unregister_mods(MOD_BIT(KC_RSFT));
        return false;
  	  } 
	    break;
    case ADD_BAR: 
   	  if(record->event.pressed) {
        layer_clear();
        SEND_STRING(SS_LCTL("l"));
        return false;
  	  } 
	    break;
    case BASE_R:
      if(record->event.pressed) {
        layer_clear();
        tap_code(KC_R);
        return false;
      }
      return true;
      break;
//below have basic keycodes for tap/hold 
    case RARROW: 
      return process_tap_or_long_press_key(record, LALT(KC_RGHT));
    case LT(0, LARROW): 
      return process_tap_or_long_press_key(record, LALT(KC_LEFT));
  }
  return true;
};


const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [0] = LAYOUT_split_3x5_2(LT(5,KC_Q), KC_W, KC_F, KC_P, KC_B, KC_J, KC_L, KC_U, KC_Y, KC_QUOT, LGUI_T(KC_A), LALT_T(KC_R), LCTL_T(KC_S), LSFT_T(KC_T), KC_G, KC_M, RSFT_T(KC_N), RCTL_T(KC_E), RALT_T(KC_I), RGUI_T(KC_O), KC_X, KC_C, KC_D, KC_V, KC_Z, KC_K, KC_H, KC_COMM, KC_DOT, KC_SLSH, KC_DEL, LT(3,KC_BSPC), LT(3,KC_SPC), TO(4)), 
    [1] = LAYOUT_split_3x5_2(PREV_TAB, SWITCH_TAB, _______, _______, MS_ACL2,
    _______, MS_BTN1, ADD_BAR, MS_BTN2, _______, KC_LGUI, BASE_R, MS_ACL1,
    MS_BTN1, ADD_BAR, CLOSE_TAB, MS_LEFT, MS_DOWN, MS_UP, MS_RGHT, KC_HOME,
    KC_PGUP, KC_PGDN, KC_END, _______, _______, MS_WHLL, MS_WHLD, MS_WHLU, MS_WHLR, _______, _______, _______, _______),
    [2] = LAYOUT_split_3x5_2(_______, _______, _______, _______, _______, _______, _______, _______, _______, _______, KC_LEFT, KC_UP, KC_DOWN, KC_RGHT, _______, _______, RSFT_T(KC_MUTE), RCTL_T(KC_VOLD), RALT_T(KC_VOLU), RGUI_T(KC_RGUI), KC_HOME, KC_PGUP, KC_PGDN, KC_END, _______, _______, _______, KC_COMM, KC_DOT, _______, _______, _______, _______, _______),
    [3] = LAYOUT_split_3x5_2(KC_GRV, KC_TILD, KC_HASH, KC_AMPR, KC_PIPE, KC_CIRC, KC_LCBR, KC_RCBR, KC_LBRC, KC_RBRC, KC_EXLM, KC_UNDS, KC_COLN, KC_EQL, KC_DLR, KC_AT, KC_LPRN, KC_RPRN, KC_UNDS, KC_SCLN, KC_PERC, KC_QUES, KC_ASTR, KC_PLUS, KC_BSLS, KC_SLSH, KC_MINS, KC_LT, KC_GT, KC_DQUO, RM_PREV, _______, _______, RM_NEXT),
    [4] = LAYOUT_split_3x5_2(KC_NO, KC_W, KC_NO, KC_P, KC_B, KC_NO, KC_NO, KC_NO, KC_Y, KC_NO, LGUI_T(KC_7), LALT_T(KC_5), LCTL_T(KC_3), LSFT_T(KC_1), CAPG, KC_NO, RSFT_T(KC_2), RCTL_T(KC_4), RALT_T(KC_6), RGUI_T(KC_8), KC_PERC, KC_NO, KC_ASTR, KC_9, KC_NO, KC_SLSH, KC_0, KC_COMM, KC_DOT, KC_NO, KC_NO, _______, _______, KC_NO),
    [5] = LAYOUT_split_3x5_2(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, QK_BOOT, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO)
};


//left vertical combos
const uint16_t PROGMEM uarrow[] = {KC_W, LALT_T(KC_R), COMBO_END};
const uint16_t PROGMEM darrow[] = {KC_F, LCTL_T(KC_S), COMBO_END};
const uint16_t PROGMEM pipe[] = {KC_P, LSFT_T(KC_T), COMBO_END};
const uint16_t PROGMEM splitWin[] = {KC_B, KC_G, COMBO_END};
//const uint16_t PROGMEM back[] = {LGUI_T(KC_A), KC_X, COMBO_END};
//const uint16_t PROGMEM scrollUp[] = {LALT_T(KC_R), KC_C, COMBO_END};
const uint16_t PROGMEM colon[] = {LCTL_T(KC_S), KC_D, COMBO_END};
const uint16_t PROGMEM equal[] = {LSFT_T(KC_T), KC_V, COMBO_END};
//right vertical combos
//const uint16_t PROGMEM quit[] = {KC_J, KC_M, COMBO_END};
const uint16_t PROGMEM larrow[] = {KC_U, RCTL_T(KC_E), COMBO_END};
const uint16_t PROGMEM rarrow[] = {KC_Y, RALT_T(KC_I), COMBO_END};
const uint16_t PROGMEM par[] = {RSFT_T(KC_N), KC_H, COMBO_END};
const uint16_t PROGMEM cur[] = {RCTL_T(KC_E), KC_COMMA, COMBO_END};
const uint16_t PROGMEM squ[] = {RALT_T(KC_I), KC_DOT, COMBO_END};

//horizontal combos
const uint16_t PROGMEM wksp1[] = {LSFT_T(KC_T), KC_G, COMBO_END};
const uint16_t PROGMEM wksp2[] = {KC_M, RSFT_T(KC_N), COMBO_END};
const uint16_t PROGMEM wksp5[] = {KC_P, KC_B, COMBO_END};
const uint16_t PROGMEM wksp6[] = {KC_J, KC_L, COMBO_END};
const uint16_t PROGMEM wksp7[] = {KC_V, KC_Z, COMBO_END};
const uint16_t PROGMEM wksp8[] = {KC_K, KC_H, COMBO_END};
//left horizontal combos
const uint16_t PROGMEM escape[] = {KC_F, KC_P, COMBO_END};
const uint16_t PROGMEM mouselayer[] = {LALT_T(KC_R), LCTL_T(KC_S), COMBO_END};
const uint16_t PROGMEM tab[] = {LALT_T(KC_R), LCTL_T(KC_S), LSFT_T(KC_T), COMBO_END};
const uint16_t PROGMEM dblpgup[] = {KC_C, KC_D, COMBO_END};
const uint16_t PROGMEM dblpgdn[] = {KC_D, KC_V, COMBO_END};
const uint16_t PROGMEM baselayer[] = {LCTL_T(KC_S), LSFT_T(KC_T), COMBO_END};
const uint16_t PROGMEM quo[] = {LALT_T(KC_R), LSFT_T(KC_T), COMBO_END};
//right horizontal combos
const uint16_t PROGMEM navlayer[] = {RCTL_T(KC_E), RALT_T(KC_I), COMBO_END};
const uint16_t PROGMEM enter[] = {RSFT_T(KC_N), RCTL_T(KC_E), RALT_T(KC_I), COMBO_END};
//const uint16_t PROGMEM leftWindow[] = {KC_H, KC_COMM, COMBO_END};
//const uint16_t PROGMEM rightWindow[] = {KC_COMM, KC_DOT, COMBO_END};
const uint16_t PROGMEM dblquo[] = {RSFT_T(KC_N), RALT_T(KC_I), COMBO_END};
//both side combos
const uint16_t PROGMEM numlayer[] = {LT(3,KC_BSPC), LT(3,KC_SPC), COMBO_END};
combo_t key_combos[] = {
    COMBO(splitWin, SPL),
    COMBO(tab, KC_TAB),
    COMBO(enter, KC_ENT), // keycodes with modifiers are possible too!
    COMBO(wksp1, WKSP1),
    COMBO(wksp2, WKSP2),
    COMBO(wksp5, LGUI(KC_5)),
    COMBO(wksp6, LGUI(KC_6)),
    COMBO(wksp7, LGUI(KC_7)),
    COMBO(wksp8, LGUI(KC_8)),
    //left horizontal combos
    COMBO(escape, KC_ESC),
    COMBO(mouselayer, TO(1)),
    COMBO(baselayer, TO(0)),
    COMBO(dblpgup, LT(0, PGUP_DBL)), //double page up when held
    COMBO(dblpgdn, LT(0, PGDN_DBL)), //double page down when held
    //left vertical combos
    COMBO(uarrow, KC_UP),
    COMBO(darrow, KC_DOWN),
    COMBO(pipe, PIPE),
    COMBO(colon, COLON),
    COMBO(equal, EQUAL),
    //right horizontal combos
    //COMBO(quit, LSG(KC_Q)),
    COMBO(numlayer, TO(4)),
    COMBO(quo, QUO),
    COMBO(dblquo, DBLQUO),
    COMBO(navlayer, TO(2)),
    //right vertical combos
    COMBO(larrow, LT(0, LARROW)), //hold causes alt + left arrow
    COMBO(rarrow, LT(0, RARROW)), //hold causes alt + right arrow
    COMBO(par, PAR),
    COMBO(cur, CUR),
    COMBO(squ, SQU),
    
};

#ifdef OTHER_KEYMAP_C
#    include OTHER_KEYMAP_C
#endif // OTHER_KEYMAP_C

//switch back to layer(0) after timeout specified in config.h
/*
void matrix_scan_user(void) {
  int state = get_highest_layer(layer_state); 
  if (state == 1 || state == 2) {
    if (last_input_activity_elapsed() > NUM_LAYER_TIMEOUT) {
      layer_move(0);
    }
  }
}
*/
