#include QMK_KEYBOARD_H
#if __has_include("keymap.h")
#    include "keymap.h"
#endif


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

/*cancel rolled modifiers

    
*/


// macro code test starts here
enum custom_keycodes {
    SPL = SAFE_RANGE,
    PGUP_DBL, //2 page scroll up 
    PGDN_DBL, //2 page scroll down
    PAR, // ()
    CUR, // {}
    SQU, // []
    QUO, // ''
    DBLQUO, // ""
    CAPG // G
};

bool process_record_user(uint16_t keycode, keyrecord_t *record) {
  switch (keycode) {
    case SPL:
    	if (record->event.pressed) {
	      tap_code16(LCTL(KC_L));
    	  tap_code16(LSFT(KC_ENT));
	      tap_code(KC_PGDN);
	    }
     	return false;
	    break;
    case PGUP_DBL:
      if (record->event.pressed) {
        tap_code(KC_PGUP);
        tap_code(KC_PGUP);
        tap_code16(RGUI(KC_LEFT));
        tap_code(KC_PGUP);
        tap_code(KC_PGUP);
      }
      return false;
      break;
    case PGDN_DBL:
      if (record->event.pressed) {
        tap_code(KC_PGDN);
        tap_code(KC_PGDN);
        tap_code16(RGUI(KC_LEFT));
        tap_code(KC_PGDN);
        tap_code(KC_PGDN);
      }
      return false;
      break;
    //cancel rolled modifiers of same hand. Prevents modifiers accidental
    //press e.g. when press s and t key, stops ctrl + t behaviour.
    case LSFT_T(KC_T):
      if (record->event.pressed && record->tap.count > 0) {
        if (get_mods() & MOD_BIT(KC_LCTL)) {
          unregister_mods(MOD_BIT(KC_LCTL));
          tap_code(KC_S);
          tap_code(KC_T);
          add_mods(MOD_BIT(KC_LCTL));
          return false;
        }
      }
      return true;
     	break;
    case RSFT_T(KC_N):
      if (record->event.pressed && record->tap.count > 0) {
        if (get_mods() & MOD_BIT(KC_RCTL)) {
          unregister_mods(MOD_BIT(KC_RCTL));
          tap_code(KC_E);
          tap_code(KC_N);
          add_mods(MOD_BIT(KC_RCTL));
          return false;
        }
      }
      return true;
    	break;
    //enter goes back baselayer if layer set
    case KC_ENT:
      if (record->event.pressed) {
        if (IS_LAYER_ON(1) 
          || IS_LAYER_ON(2) 
          || IS_LAYER_ON(3)
          || IS_LAYER_ON(4)) {
          tap_code(KC_ENT);
          layer_clear();       
          return false;
        }
      }
      return true;
      break;
    //space key goes back to default layer from all layer
    case LT(3,KC_SPC):
      if (record->event.pressed) {
        if (IS_LAYER_ON(1) 
          || IS_LAYER_ON(2) 
          || IS_LAYER_ON(3)
          || IS_LAYER_ON(4)) {
          tap_code(KC_SPC);
          layer_clear();       
          return false;
        }
      }
      return true;
      break;
    //escape goes back baselayer if layer set
    case KC_ESC:
      if (record->event.pressed) {
        if (IS_LAYER_ON(1) || IS_LAYER_ON(2) || IS_LAYER_ON(4)) {
          layer_clear();       
          return false;
        }
      }
      return true;
      break;
    //macro for brackets
    case PAR: 
      if (record->event.pressed) {
	    //if shift pressed
        if(get_mods() & MOD_BIT(KC_LSFT)) {
          unregister_mods(MOD_BIT(KC_LSFT));	
	        SEND_STRING("()" SS_TAP(X_LEFT));
          add_mods(MOD_BIT(KC_LSFT));
          return false;
	    //if no shift pressed
        } else {
	        SEND_STRING("()"); 
        }
      } 
      return true;
      break;
    case CUR: 
      if(record->event.pressed) {
        if(get_mods() & MOD_BIT(KC_LSFT)) {
          unregister_mods(MOD_BIT(KC_LSFT));	
	        SEND_STRING("{}" SS_TAP(X_LEFT));
          add_mods(MOD_BIT(KC_LSFT));
          return false;
	    //if no shift pressed
        } else {
	        SEND_STRING("{}"); 
        }
      } 
      return true;
      break;
    case SQU: 
      if(record->event.pressed) {
	      if(get_mods() & MOD_BIT(KC_LSFT)) {
          unregister_mods(MOD_BIT(KC_LSFT));	
          SEND_STRING("[]" SS_TAP(X_LEFT));
          add_mods(MOD_BIT(KC_LSFT));
          return false;
	      //if no shift pressed
	      } else {
          SEND_STRING("[]"); 
	      }
      } 
      return true;
      break;
    //below needs to be added to combos to use right pinky keys
    case QUO: 
   	  if(record->event.pressed) {
  	    if(get_mods() & MOD_BIT(KC_LSFT)) {
  	     	unregister_mods(MOD_BIT(KC_LSFT));	
  	      SEND_STRING("''" SS_TAP(X_LEFT));
  		    add_mods(MOD_BIT(KC_LSFT));
  		    return false;
  	    //if no shift pressed
  	    } else {
  	      SEND_STRING("''"); 
  	    }
  	  } 
      return true;
	    break;
    case DBLQUO: 
   	  if(record->event.pressed) {
  	    if(get_mods() & MOD_BIT(KC_LSFT)) {
  	     	unregister_mods(MOD_BIT(KC_LSFT));	
  	      SEND_STRING("\"\"" SS_TAP(X_LEFT));
  		    add_mods(MOD_BIT(KC_LSFT));
  		    return false;
  	    //if no shift pressed
  	    } else {
  	      SEND_STRING("\"\""); 
  	    }
  	  } 
      return true;
	    break;
    case CAPG: 
   	  if(record->event.pressed) {
        register_mods(MOD_BIT(KC_RSFT));
        tap_code(KC_G);
        layer_clear();
        unregister_mods(MOD_BIT(KC_RSFT));
        return false;
  	  } 
      return true;
	    break;
  }
  return true;
};


const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [0] = LAYOUT_split_3x5_2(LT(5,KC_Q), KC_W, KC_F, KC_P, KC_B, KC_J, KC_L, KC_U, KC_Y, KC_QUOT, LGUI_T(KC_A), LALT_T(KC_R), LCTL_T(KC_S), LSFT_T(KC_T), KC_G, KC_M, RSFT_T(KC_N), RCTL_T(KC_E), RALT_T(KC_I), RGUI_T(KC_O), KC_X, KC_C, KC_D, KC_V, KC_Z, KC_K, KC_H, KC_COMM, KC_DOT, KC_SLSH, KC_DEL, LT(3,KC_BSPC), LT(3,KC_SPC), TG(2)), 
    [1] = LAYOUT_split_3x5_2(KC_TRNS, MS_BTN2, KC_TRNS, MS_BTN1, KC_TRNS, KC_TRNS, MS_BTN1, MS_WHLU, MS_BTN2, KC_TRNS, KC_TRNS, MS_ACL0, MS_ACL1, MS_ACL2, KC_TRNS, KC_TRNS, MS_LEFT, MS_DOWN, MS_UP, MS_RGHT, KC_TRNS, KC_PGUP, KC_PGDN, KC_TRNS, KC_TRNS, KC_TRNS, MS_WHLL, MS_WHLD, MS_WHLU, MS_WHLR, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),
    [2] = LAYOUT_split_3x5_2(KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_LEFT, KC_UP, KC_DOWN, KC_RGHT, KC_TRNS, KC_TRNS, RSFT_T(KC_NO), RCTL_T(KC_NO), RALT_T(KC_NO), RGUI_T(KC_RGUI), KC_HOME, PGUP_DBL, PGDN_DBL, KC_END, KC_TRNS, KC_TRNS, KC_TRNS, KC_COMM, KC_DOT, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),
    [3] = LAYOUT_split_3x5_2(KC_GRV, KC_TILD, KC_HASH, KC_AMPR, KC_PIPE, KC_CIRC, KC_LCBR, KC_RCBR, KC_LBRC, KC_RBRC, KC_EXLM, KC_UNDS, KC_COLN, KC_EQL, KC_DLR, KC_AT, KC_LPRN, KC_RPRN, KC_UNDS, KC_SCLN, KC_PERC, KC_QUES, KC_ASTR, KC_PLUS, KC_BSLS, KC_SLSH, KC_MINS, KC_LT, KC_GT, KC_DQUO, RM_PREV, KC_TRNS, KC_TRNS, RM_NEXT),
    [4] = LAYOUT_split_3x5_2(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, LGUI_T(KC_7), LALT_T(KC_5), LCTL_T(KC_3), LSFT_T(KC_1), CAPG, KC_NO, RSFT_T(KC_2), RCTL_T(KC_4), RALT_T(KC_6), RGUI_T(KC_8), KC_PERC, KC_NO, KC_ASTR, KC_9, KC_NO, KC_SLSH, KC_0, KC_COMM, KC_DOT, KC_NO, KC_NO, KC_TRNS, KC_TRNS, KC_NO),
    [5] = LAYOUT_split_3x5_2(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, QK_BOOT, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO)
};


const uint16_t PROGMEM splitWin[] = {LT(5,KC_Q), LGUI_T(KC_A), COMBO_END};
const uint16_t PROGMEM leftWindow[] = {KC_W, LALT_T(KC_R), COMBO_END};
const uint16_t PROGMEM rightWindow[] = {KC_Y, RALT_T(KC_I), COMBO_END};
//const uint16_t PROGMEM tab[] = {KC_F, LCTL_T(KC_S), COMBO_END};
const uint16_t PROGMEM esc[] = {KC_P, LSFT_T(KC_T), COMBO_END};
//const uint16_t PROGMEM enter[] = {KC_U, RCTL_T(KC_E), COMBO_END};

const uint16_t PROGMEM back[] = {LGUI_T(KC_A), KC_X, COMBO_END};
const uint16_t PROGMEM forward[] = {LSFT_T(KC_T), KC_V, COMBO_END};

//left vertical combos
//const uint16_t PROGMEM mouselayer[] = {KC_F, LCTL_T(KC_S), COMBO_END};
const uint16_t PROGMEM scrollUp[] = {LALT_T(KC_R), KC_C, COMBO_END};
const uint16_t PROGMEM scrollDown[] = {LCTL_T(KC_S), KC_D, COMBO_END};
//right vertical combos
//const uint16_t PROGMEM baselayer[] = {KC_L, RSFT_T(KC_N), COMBO_END};
//const uint16_t PROGMEM navlayer[] = {KC_U, RCTL_T(KC_E), COMBO_END};
const uint16_t PROGMEM par[] = {RSFT_T(KC_N), KC_H, COMBO_END};
const uint16_t PROGMEM cur[] = {RCTL_T(KC_E), KC_COMMA, COMBO_END};
const uint16_t PROGMEM squ[] = {RALT_T(KC_I), KC_DOT, COMBO_END};


//horizontal combos
const uint16_t PROGMEM wksp1[] = {LSFT_T(KC_T), KC_G, COMBO_END};
const uint16_t PROGMEM wksp2[] = {KC_M, RSFT_T(KC_N), COMBO_END};
const uint16_t PROGMEM wksp3[] = {KC_V, KC_Z, COMBO_END};
const uint16_t PROGMEM wksp4[] = {KC_K, KC_H, COMBO_END};
const uint16_t PROGMEM wksp5[] = {KC_P, KC_B, COMBO_END};
const uint16_t PROGMEM wksp6[] = {KC_J, KC_L, COMBO_END};
//left horizontal combos
const uint16_t PROGMEM mouselayer[] = {LALT_T(KC_R), LCTL_T(KC_S), COMBO_END};
const uint16_t PROGMEM tab[] = {LALT_T(KC_R), LCTL_T(KC_S), LSFT_T(KC_T), COMBO_END};
const uint16_t PROGMEM dblpgup[] = {KC_C, KC_D, COMBO_END};
const uint16_t PROGMEM dblpgdn[] = {KC_D, KC_V, COMBO_END};
const uint16_t PROGMEM escape[] = {LCTL_T(KC_S), LSFT_T(KC_T), COMBO_END};
//right horizontal combos
const uint16_t PROGMEM navlayer[] = {RCTL_T(KC_E), RALT_T(KC_I), COMBO_END};
const uint16_t PROGMEM enter[] = {RSFT_T(KC_N), RCTL_T(KC_E), RALT_T(KC_I), COMBO_END};
const uint16_t PROGMEM quo[] = {KC_H, KC_COMM, COMBO_END};
const uint16_t PROGMEM dblquo[] = {KC_COMM, KC_DOT, COMBO_END};
//both side combos
const uint16_t PROGMEM numlayer[] = {LT(3,KC_BSPC), LT(3,KC_SPC), COMBO_END};
combo_t key_combos[] = {
    COMBO(splitWin, SPL),
    COMBO(tab, KC_TAB),
    COMBO(esc, KC_ESC),
    COMBO(escape, KC_ESC),
    COMBO(enter, KC_ENT), // keycodes with modifiers are possible too!
    COMBO(back, KC_WBAK),
    COMBO(scrollUp, KC_PGUP), 
    COMBO(scrollDown, KC_PGDN), 
    COMBO(forward, KC_WFWD),
    COMBO(leftWindow, LGUI(KC_LEFT)),
    COMBO(rightWindow, LGUI(KC_RGHT)),
    COMBO(wksp1, LGUI(KC_1)),
    COMBO(wksp2, LGUI(KC_2)),
    COMBO(wksp3, LGUI(KC_3)),
    COMBO(wksp4, LGUI(KC_4)),
    COMBO(wksp5, LGUI(KC_5)),
    COMBO(wksp6, LGUI(KC_6)),
    //left horizontal combos
    COMBO(dblpgup, PGUP_DBL),
    COMBO(dblpgdn, PGDN_DBL),
    //left vertical combos
    COMBO(mouselayer, TO(1)),
    //mouse layer, left vertical combos
    //COMBO(mouselayeroff, TG(1)),
    //COMBO(mousepgup_dbl, PGUP_DBL),
    //COMBO(mousepgdn_dbl, PGDN_DBL),
    //right vertical combos
    COMBO(numlayer, TO(4)),
    COMBO(quo, QUO),
    COMBO(dblquo, DBLQUO),
    COMBO(navlayer, TO(2)),
    COMBO(par, PAR),
    COMBO(cur, CUR),
    COMBO(squ, SQU),
    //right vertical combos
    //mouse layer, right vertical combos
    //COMBO(navlayeroff, TG(2)),
    
};

#ifdef OTHER_KEYMAP_C
#    include OTHER_KEYMAP_C
#endif // OTHER_KEYMAP_C

//switch back to layer(0) after timeout specified in config.h
void matrix_scan_user(void) {
  int state = get_highest_layer(layer_state); 
  if (state == 1 || state == 2) {
    if (last_input_activity_elapsed() > NUM_LAYER_TIMEOUT) {
      layer_move(0);
    }
  }
}
